//header automatically generated by autoHead
#pragma once
#include<stddef.h>
#include "libs/gal_mult.h"
void key_remove(char* byte_data, char key);
void row_unshift(char* row);
void col_unmix(char* col);
void col_unshift(char* byte_data);
void decrypt_data(char* byte_data, char* key, size_t key_len);
