//header automatically generated by autoHead
void key_remove(char* byte_data, char key);
void row_unshift(char* byte_data, char* key, size_t key_len, int row);
void col_unshift(char* byte_data, char* key,size_t key_s, int col);
void decrypt_data(char* byte_data, char* key, size_t key_len);
