//header automatically generated by autoHead
#pragma once
#include <stdlib.h>
#include "libs/gal_mult.h"
void row_shift(char* row);
void col_mix(char* col);
void col_shift(char* byte_data, char* key,size_t key_s, int col);
void key_apply(char* byte_data, char key);
 //in place encryption, assumes 16 bytes of data
void encrypt_data(char* byte_data, char* key, size_t k_len);
